version: '3.8'

services:
  go-server:
    build:
      context: ./go-server  # Path to the Go server folder
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/blogDB
    env_file:
      - ./go-server/.env
    depends_on:
      - mongo
    # restart: always

  nextjs:
    build:
      context: ./nextwithgo  # Path to the Next.js folder
    ports:
      - "3000:3000"          # Expose port 3000 for Next.js
    environment:
      - NODE_ENV=production
    depends_on:
      - go-server
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # restart: always

volumes:
  mongo_data:

